spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finwise
    username: finuser
    password: finpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: finwise
